
export const countryCodes = [
  { value: "+93", label: "AFG +93", country: "Afghanistan" },
  { value: "+355", label: "ALB +355", country: "Albania" },
  { value: "+213", label: "DZA +213", country: "Algeria" },
  { value: "+376", label: "AND +376", country: "Andorra" },
  { value: "+244", label: "AGO +244", country: "Angola" },
  { value: "+54", label: "ARG +54", country: "Argentina" },
  { value: "+374", label: "ARM +374", country: "Armenia" },
  { value: "+61", label: "AUS +61", country: "Australia" },
  { value: "+43", label: "AUT +43", country: "Austria" },
  { value: "+994", label: "AZE +994", country: "Azerbaijan" },
  { value: "+973", label: "BHR +973", country: "Bahrain" },
  { value: "+880", label: "BGD +880", country: "Bangladesh" },
  { value: "+375", label: "BLR +375", country: "Belarus" },
  { value: "+32", label: "BEL +32", country: "Belgium" },
  { value: "+501", label: "BLZ +501", country: "Belize" },
  { value: "+229", label: "BEN +229", country: "Benin" },
  { value: "+975", label: "BTN +975", country: "Bhutan" },
  { value: "+591", label: "BOL +591", country: "Bolivia" },
  { value: "+387", label: "BIH +387", country: "Bosnia and Herzegovina" },
  { value: "+267", label: "BWA +267", country: "Botswana" },
  { value: "+55", label: "BRA +55", country: "Brazil" },
  { value: "+673", label: "BRN +673", country: "Brunei" },
  { value: "+359", label: "BGR +359", country: "Bulgaria" },
  { value: "+226", label: "BFA +226", country: "Burkina Faso" },
  { value: "+257", label: "BDI +257", country: "Burundi" },
  { value: "+855", label: "KHM +855", country: "Cambodia" },
  { value: "+237", label: "CMR +237", country: "Cameroon" },
  { value: "+1", label: "CAN +1", country: "Canada/USA" },
  { value: "+238", label: "CPV +238", country: "Cape Verde" },
  { value: "+236", label: "CAF +236", country: "Central African Republic" },
  { value: "+235", label: "TCD +235", country: "Chad" },
  { value: "+56", label: "CHL +56", country: "Chile" },
  { value: "+86", label: "CHN +86", country: "China" },
  { value: "+57", label: "COL +57", country: "Colombia" },
  { value: "+269", label: "COM +269", country: "Comoros" },
  { value: "+242", label: "COG +242", country: "Congo" },
  { value: "+506", label: "CRI +506", country: "Costa Rica" },
  { value: "+385", label: "HRV +385", country: "Croatia" },
  { value: "+53", label: "CUB +53", country: "Cuba" },
  { value: "+357", label: "CYP +357", country: "Cyprus" },
  { value: "+420", label: "CZE +420", country: "Czech Republic" },
  { value: "+45", label: "DNK +45", country: "Denmark" },
  { value: "+253", label: "DJI +253", country: "Djibouti" },
  { value: "+593", label: "ECU +593", country: "Ecuador" },
  { value: "+20", label: "EGY +20", country: "Egypt" },
  { value: "+503", label: "SLV +503", country: "El Salvador" },
  { value: "+240", label: "GNQ +240", country: "Equatorial Guinea" },
  { value: "+291", label: "ERI +291", country: "Eritrea" },
  { value: "+372", label: "EST +372", country: "Estonia" },
  { value: "+251", label: "ETH +251", country: "Ethiopia" },
  { value: "+679", label: "FJI +679", country: "Fiji" },
  { value: "+358", label: "FIN +358", country: "Finland" },
  { value: "+33", label: "FRA +33", country: "France" },
  { value: "+241", label: "GAB +241", country: "Gabon" },
  { value: "+220", label: "GMB +220", country: "Gambia" },
  { value: "+995", label: "GEO +995", country: "Georgia" },
  { value: "+49", label: "DEU +49", country: "Germany" },
  { value: "+233", label: "GHA +233", country: "Ghana" },
  { value: "+30", label: "GRC +30", country: "Greece" },
  { value: "+502", label: "GTM +502", country: "Guatemala" },
  { value: "+224", label: "GIN +224", country: "Guinea" },
  { value: "+245", label: "GNB +245", country: "Guinea-Bissau" },
  { value: "+592", label: "GUY +592", country: "Guyana" },
  { value: "+509", label: "HTI +509", country: "Haiti" },
  { value: "+504", label: "HND +504", country: "Honduras" },
  { value: "+852", label: "HKG +852", country: "Hong Kong" },
  { value: "+36", label: "HUN +36", country: "Hungary" },
  { value: "+354", label: "ISL +354", country: "Iceland" },
  { value: "+91", label: "IND +91", country: "India" },
  { value: "+62", label: "IDN +62", country: "Indonesia" },
  { value: "+98", label: "IRN +98", country: "Iran" },
  { value: "+964", label: "IRQ +964", country: "Iraq" },
  { value: "+353", label: "IRL +353", country: "Ireland" },
  { value: "+972", label: "ISR +972", country: "Israel" },
  { value: "+39", label: "ITA +39", country: "Italy" },
  { value: "+225", label: "CIV +225", country: "Ivory Coast" },
  { value: "+81", label: "JPN +81", country: "Japan" },
  { value: "+962", label: "JOR +962", country: "Jordan" },
  { value: "+7", label: "KAZ +7", country: "Kazakhstan" },
  { value: "+254", label: "KEN +254", country: "Kenya" },
  { value: "+965", label: "KWT +965", country: "Kuwait" },
  { value: "+996", label: "KGZ +996", country: "Kyrgyzstan" },
  { value: "+856", label: "LAO +856", country: "Laos" },
  { value: "+371", label: "LVA +371", country: "Latvia" },
  { value: "+961", label: "LBN +961", country: "Lebanon" },
  { value: "+266", label: "LSO +266", country: "Lesotho" },
  { value: "+231", label: "LBR +231", country: "Liberia" },
  { value: "+218", label: "LBY +218", country: "Libya" },
  { value: "+423", label: "LIE +423", country: "Liechtenstein" },
  { value: "+370", label: "LTU +370", country: "Lithuania" },
  { value: "+352", label: "LUX +352", country: "Luxembourg" },
  { value: "+261", label: "MDG +261", country: "Madagascar" },
  { value: "+265", label: "MWI +265", country: "Malawi" },
  { value: "+60", label: "MYS +60", country: "Malaysia" },
  { value: "+960", label: "MDV +960", country: "Maldives" },
  { value: "+223", label: "MLI +223", country: "Mali" },
  { value: "+356", label: "MLT +356", country: "Malta" },
  { value: "+222", label: "MRT +222", country: "Mauritania" },
  { value: "+230", label: "MUS +230", country: "Mauritius" },
  { value: "+52", label: "MEX +52", country: "Mexico" },
  { value: "+373", label: "MDA +373", country: "Moldova" },
  { value: "+377", label: "MCO +377", country: "Monaco" },
  { value: "+976", label: "MNG +976", country: "Mongolia" },
  { value: "+382", label: "MNE +382", country: "Montenegro" },
  { value: "+212", label: "MAR +212", country: "Morocco" },
  { value: "+258", label: "MOZ +258", country: "Mozambique" },
  { value: "+95", label: "MMR +95", country: "Myanmar" },
  { value: "+264", label: "NAM +264", country: "Namibia" },
  { value: "+977", label: "NPL +977", country: "Nepal" },
  { value: "+31", label: "NLD +31", country: "Netherlands" },
  { value: "+64", label: "NZL +64", country: "New Zealand" },
  { value: "+505", label: "NIC +505", country: "Nicaragua" },
  { value: "+227", label: "NER +227", country: "Niger" },
  { value: "+234", label: "NGA +234", country: "Nigeria" },
  { value: "+850", label: "PRK +850", country: "North Korea" },
  { value: "+389", label: "MKD +389", country: "North Macedonia" },
  { value: "+47", label: "NOR +47", country: "Norway" },
  { value: "+968", label: "OMN +968", country: "Oman" },
  { value: "+92", label: "PAK +92", country: "Pakistan" },
  { value: "+970", label: "PSE +970", country: "Palestine" },
  { value: "+507", label: "PAN +507", country: "Panama" },
  { value: "+675", label: "PNG +675", country: "Papua New Guinea" },
  { value: "+595", label: "PRY +595", country: "Paraguay" },
  { value: "+51", label: "PER +51", country: "Peru" },
  { value: "+63", label: "PHL +63", country: "Philippines" },
  { value: "+48", label: "POL +48", country: "Poland" },
  { value: "+351", label: "PRT +351", country: "Portugal" },
  { value: "+974", label: "QAT +974", country: "Qatar" },
  { value: "+40", label: "ROU +40", country: "Romania" },
  { value: "+250", label: "RWA +250", country: "Rwanda" },
  { value: "+966", label: "SAU +966", country: "Saudi Arabia" },
  { value: "+221", label: "SEN +221", country: "Senegal" },
  { value: "+381", label: "SRB +381", country: "Serbia" },
  { value: "+248", label: "SYC +248", country: "Seychelles" },
  { value: "+232", label: "SLE +232", country: "Sierra Leone" },
  { value: "+65", label: "SGP +65", country: "Singapore" },
  { value: "+421", label: "SVK +421", country: "Slovakia" },
  { value: "+386", label: "SVN +386", country: "Slovenia" },
  { value: "+252", label: "SOM +252", country: "Somalia" },
  { value: "+27", label: "ZAF +27", country: "South Africa" },
  { value: "+82", label: "KOR +82", country: "South Korea" },
  { value: "+211", label: "SSD +211", country: "South Sudan" },
  { value: "+34", label: "ESP +34", country: "Spain" },
  { value: "+94", label: "LKA +94", country: "Sri Lanka" },
  { value: "+249", label: "SDN +249", country: "Sudan" },
  { value: "+597", label: "SUR +597", country: "Suriname" },
  { value: "+46", label: "SWE +46", country: "Sweden" },
  { value: "+41", label: "CHE +41", country: "Switzerland" },
  { value: "+963", label: "SYR +963", country: "Syria" },
  { value: "+886", label: "TWN +886", country: "Taiwan" },
  { value: "+992", label: "TJK +992", country: "Tajikistan" },
  { value: "+255", label: "TZA +255", country: "Tanzania" },
  { value: "+66", label: "THA +66", country: "Thailand" },
  { value: "+228", label: "TGO +228", country: "Togo" },
  { value: "+216", label: "TUN +216", country: "Tunisia" },
  { value: "+90", label: "TUR +90", country: "Turkey" },
  { value: "+993", label: "TKM +993", country: "Turkmenistan" },
  { value: "+256", label: "UGA +256", country: "Uganda" },
  { value: "+380", label: "UKR +380", country: "Ukraine" },
  { value: "+971", label: "ARE +971", country: "United Arab Emirates" },
  { value: "+44", label: "GBR +44", country: "United Kingdom" },
  { value: "+598", label: "URY +598", country: "Uruguay" },
  { value: "+998", label: "UZB +998", country: "Uzbekistan" },
  { value: "+678", label: "VUT +678", country: "Vanuatu" },
  { value: "+58", label: "VEN +58", country: "Venezuela" },
  { value: "+84", label: "VNM +84", country: "Vietnam" },
  { value: "+967", label: "YEM +967", country: "Yemen" },
  { value: "+260", label: "ZMB +260", country: "Zambia" },
  { value: "+263", label: "ZWE +263", country: "Zimbabwe" },
];